### ISSUE TITLE
Dynamic byline behaves erratically

### ISSUE THREAD

**Issue by EweSparky** [Kikobeats/kikobeats.com#10]
Hi there,

FYI - the website byline that dynamically replaces text causes the entire website to flicker. Please see the attached video.

https://drive.google.com/file/d/1n79487lTOFOD7ybg7Lw2k_ahZRnSioeC/view?usp=sharing

Windows 10 1803
Firefox 63.0.3

It does it in private browsing, so I don't think it's an extension misbehaving.

**Comment by Kikobeats** [comment]
Thanks, closed at https://github.com/Kikobeats/kikobeats.com/commit/9a26489dc04d9a6784d4007cee5942020f402f92

I decided temporarily disabled the library, looks a bug related with it :((
